package fr.limsi.rorqual.core.dpe.enums.chauffageproperties;

/**
 * Created by ricordeau on 21/07/15.
 */
public enum TypeChauffageEnum {
    CHAUFFAGE_ELETRIQUE,
    CHAUDIERE_GAZ_CLASSIQUE,
    CHAUDIERE_GAZ_BASSE_TEMPERATURE,
    CHAUDIERE_GAZ_CONDENSATION,
    CHAUDIERE_FIOUL_CLASSIQUE,
    CHAUDIERE_FIOUL_BASSE_TEMPERATURE,
    CHAUDIERE_FIOUL_CONDENSATION,
    CHAUDIERE_ELECTRIQUE,
    CHAUDIERE_BOIS,
    POMPE_A_CHALEUR,
    RADIATEUR_A_GAZ,
    POELE_OU_INSERT,;
}
