package fr.limsi.rorqual.core.dpe;

import fr.limsi.rorqual.core.event.EventType;

/**
 * Created by christophe on 03/06/15.
 */
public enum DpeEvent implements EventType {
    START_DPE,
    START_DPE_RESPONSE,
    TYPE_BATIMENT,
    TYPE_BATIMENT_RESPONSE,
    NB_NIVEAUX,
    NB_NIVEAUX_RESPONSE,
    FORME,
    FORME_RESPONSE,
    MITOYENNETE,
    MITOYENNETE_RESPONSE,
    POSITION_APPARTEMENT,
    POSITION_APPARTEMENT_RESPONSE,
    ANNEE_CONSTRUCTION,
    ANNEE_CONSTRUCTION_RESPONSE,
    ENERGIE_CONSTRUCTION,
    ENERGIE_CONSTRUCTION_RESPONSE,
    DERRIERE_MUR,
    DERRIERE_MUR_RESPONSE,
    DPE_STATE_CHANGED,
    ;
}
