package fr.limsi.rorqual.core.dpe;

/**
 * Created by ricordeau on 06/07/15.
 */
public enum TypeDoorEnum {
    PORTE_OPAQUE_PLEINE,
    PORTE_AVEC_MOIS_DE_30_POURCENT_DE_SIMPLE_VITRAGE,
    PORTE_AVEC_30_60_POURCENT_DE_SIMPLE_VITRAGE,
    PORTE_AVEC_DOUBLE_VITRAGE,
    PORTE_OPAQUE_PLEINE_ISOLEE,
    PORTE_PRECEDE_DUN_SAS,
    PORTE_FENETRE_BATTANTE,
    PORTE_FENETRE_COULISSANTE,
    UNKNOWN;
}
