package fr.limsi.rorqual.core.dpe.enums.ecsproperties;

/**
 * Created by ricordeau on 29/07/15.
 */
public enum TypeEquipementEcsEnum {
    CHAUDIERE,
    BALLON_ELECTRIQUE_HORIZONTAL_INF_15ANS,
    BALLON_ELECTRIQUE_HORIZONTAL_SUP_15ANS,
    BALLON_ELECTRIQUE_VERTICAL_INF_15ANS,
    BALLON_ELECTRIQUE_VERTICAL_SUP_15ANS,
    CHAUFFE_EAU_THERMODYNAMIQUE_SUR_AIR_EXTRAIT,
    CHAUFFE_EAU_THERMODYNAMIQUE_SUR_AIR_EXTERIEUR,
    CHAUFFE_EAU_GAZ_INF_1991,
    CHAUFFE_EAU_GAZ_ENTRE_1991_2002,
    CHAUFFE_EAU_GAZ_SUP_2003,
    ACCUMULATEUR_GAZ_CLASSIQUE_INF_1991,
    ACCUMULATEUR_GAZ_CLASSIQUE_ENTRE_1991_2002,
    ACCUMULATEUR_GAZ_CLASSIQUE_SUP_2003,
    ACCUMULATEUR_GAZ_CONDENSATION;
}
