package fr.limsi.rorqual.core.event;

/**
 * Created by christophe on 03/06/15.
 */
public enum DpeEvent implements EventType {
    START_DPE,
    TYPE_BATIMENT,
    NB_NIVEAUX_MAISON,
    FORME_MAISON,
    MITOYENNETE_MAISON,
    POSITION_APPARTEMENT,
    ANNEE_CONSTRUCTION,
    ENERGIE_CONSTRUCTION,
    TYPE_VENTILATION,

    TYPE_MUR,
    DATE_ISOLATION_MUR,
    TYPE_ISOLATION_MUR,
    TYPE_FENETRE,
    TYPE_PORTE,
    TYPE_MATERIAU_MENUISERIE,
    TYPE_VITRAGE_MENUISERIE,
    TYPE_FERMETURE_MENUISERIE,

    DPE_STATE_CHANGED,
    DPE_STATE_REQUIRED,
    DPE_REQUEST,
    DPE_STATE_NO_MORE_WALL_UNKNOWN,
    DPE_STATE_NO_MORE_UNKNOWN,
    ;
}
