package fr.limsi.rorqual.core.event;

/**
 * Created by christophe on 03/06/15.
 */
public enum DpeEvent implements EventType {
    INFOS_GENERALES,
    INFOS_CHAUFFAGE,

    TYPE_BATIMENT,
    NB_NIVEAUX_MAISON,
    FORME_MAISON,
    MITOYENNETE_MAISON,
    POSITION_APPARTEMENT,
    ANNEE_CONSTRUCTION,
    ENERGIE_CONSTRUCTION,
    TYPE_VENTILATION,

    TYPE_CHAUFFAGE_PRINCIPAL,
    TYPE_CHAUFFAGE_SECONDAIRE,
    TYPE_POMPE_A_CHALEUR,
    TYPE_POIL_OU_INSERT,
    DATE_CHAUDIERE_GAZ_CLASSIQUE,
    DATE_CHAUDIERE_GAZ_CONDENSATION,
    DATE_CHAUDIERE_GAZ_BASSE_TEMPERATURE,
    DATE_CHAUDIERE_FIOUL,
    AGE_CHAUDIERE_BOIS,
    AGE_CHAUFFAGE_ELECTRIQUE,
    TEMPERATURE_INTERIEUR,
    TYPE_EMETTEUR_DE_CHALEUR,
    PRESENCE_THERMOSTAT_OU_SONDE_EXTERIEUR,
    PRESENCE_ROBINET_THERMOSTATIQUE,
    SYSTEME_PROGRAMMABLE,
    FREQUENCE_UTILISATION_POIL_OU_INSERT,

    TYPE_MUR,
    DATE_ISOLATION_MUR,
    TYPE_ISOLATION_MUR,
    ORIENTATION_MUR,
    TYPE_FENETRE,
    TYPE_PORTE,
    TYPE_MATERIAU_MENUISERIE,
    TYPE_VITRAGE_MENUISERIE,
    TYPE_FERMETURE_MENUISERIE,

    DPE_STATE_CHANGED,
    DPE_STATE_REQUIRED,
    DPE_REQUEST,
    DPE_STATE_NO_MORE_WALL_UNKNOWN,
    DPE_STATE_NO_MORE_UNKNOWN,
    ;
}
